/*
-- Query: SELECT * FROM routes_city.route
LIMIT 0, 1000

-- Date: 2018-09-15 15:24
*/
INSERT INTO `route` (`idroute`,`name`) VALUES (1,'1');
INSERT INTO `route` (`idroute`,`name`) VALUES (2,'2');
INSERT INTO `route` (`idroute`,`name`) VALUES (3,'3A');
INSERT INTO `route` (`idroute`,`name`) VALUES (4,'3');
INSERT INTO `route` (`idroute`,`name`) VALUES (5,'4 CIRCULAR');
INSERT INTO `route` (`idroute`,`name`) VALUES (6,'4');
INSERT INTO `route` (`idroute`,`name`) VALUES (7,'5');
INSERT INTO `route` (`idroute`,`name`) VALUES (8,'6');
INSERT INTO `route` (`idroute`,`name`) VALUES (9,'6A');
INSERT INTO `route` (`idroute`,`name`) VALUES (10,'6');
INSERT INTO `route` (`idroute`,`name`) VALUES (11,'7');
INSERT INTO `route` (`idroute`,`name`) VALUES (12,'7A');
INSERT INTO `route` (`idroute`,`name`) VALUES (13,'8');
INSERT INTO `route` (`idroute`,`name`) VALUES (14,'9');
INSERT INTO `route` (`idroute`,`name`) VALUES (15,'10');
INSERT INTO `route` (`idroute`,`name`) VALUES (16,'11');
INSERT INTO `route` (`idroute`,`name`) VALUES (17,'12');
INSERT INTO `route` (`idroute`,`name`) VALUES (18,'12A');
INSERT INTO `route` (`idroute`,`name`) VALUES (19,'13');
INSERT INTO `route` (`idroute`,`name`) VALUES (20,'13A');
INSERT INTO `route` (`idroute`,`name`) VALUES (21,'14 ALEGRIAS');
INSERT INTO `route` (`idroute`,`name`) VALUES (22,'14');
INSERT INTO `route` (`idroute`,`name`) VALUES (23,'14C');
INSERT INTO `route` (`idroute`,`name`) VALUES (24,'14 LAGUNETA');
INSERT INTO `route` (`idroute`,`name`) VALUES (25,'14 MONTELARGO');
INSERT INTO `route` (`idroute`,`name`) VALUES (26,'15');
INSERT INTO `route` (`idroute`,`name`) VALUES (27,'16');
INSERT INTO `route` (`idroute`,`name`) VALUES (28,'17');
INSERT INTO `route` (`idroute`,`name`) VALUES (29,'17 CIRCULAR');
INSERT INTO `route` (`idroute`,`name`) VALUES (30,'17A');
INSERT INTO `route` (`idroute`,`name`) VALUES (31,'18');
INSERT INTO `route` (`idroute`,`name`) VALUES (32,'19');
INSERT INTO `route` (`idroute`,`name`) VALUES (33,'20');
INSERT INTO `route` (`idroute`,`name`) VALUES (34,'20A');
INSERT INTO `route` (`idroute`,`name`) VALUES (35,'21');
INSERT INTO `route` (`idroute`,`name`) VALUES (36,'22');
INSERT INTO `route` (`idroute`,`name`) VALUES (37,'23');
INSERT INTO `route` (`idroute`,`name`) VALUES (38,'23 CIRCULAR');
INSERT INTO `route` (`idroute`,`name`) VALUES (39,'24');
INSERT INTO `route` (`idroute`,`name`) VALUES (40,'24A');
INSERT INTO `route` (`idroute`,`name`) VALUES (41,'25');
INSERT INTO `route` (`idroute`,`name`) VALUES (42,'25A');
INSERT INTO `route` (`idroute`,`name`) VALUES (43,'26');
INSERT INTO `route` (`idroute`,`name`) VALUES (44,'27 SITM');
INSERT INTO `route` (`idroute`,`name`) VALUES (45,'27');
INSERT INTO `route` (`idroute`,`name`) VALUES (46,'28');
INSERT INTO `route` (`idroute`,`name`) VALUES (47,'29');
INSERT INTO `route` (`idroute`,`name`) VALUES (48,'30');
INSERT INTO `route` (`idroute`,`name`) VALUES (49,'31');
INSERT INTO `route` (`idroute`,`name`) VALUES (50,'31A');
INSERT INTO `route` (`idroute`,`name`) VALUES (51,'32 LA BODEGA');
INSERT INTO `route` (`idroute`,`name`) VALUES (52,'32');
INSERT INTO `route` (`idroute`,`name`) VALUES (53,'32 SAN MARINO');
INSERT INTO `route` (`idroute`,`name`) VALUES (54,'32 LA SUECIA');
INSERT INTO `route` (`idroute`,`name`) VALUES (55,'33');
INSERT INTO `route` (`idroute`,`name`) VALUES (56,'33A');
INSERT INTO `route` (`idroute`,`name`) VALUES (57,'34');
INSERT INTO `route` (`idroute`,`name`) VALUES (58,'35');
INSERT INTO `route` (`idroute`,`name`) VALUES (59,'35 CIRCULAR');
INSERT INTO `route` (`idroute`,`name`) VALUES (60,'35 EL RETIRO');
INSERT INTO `route` (`idroute`,`name`) VALUES (61,'35 TRES PUERTAS');
INSERT INTO `route` (`idroute`,`name`) VALUES (62,'35 RIO BARBAS');
INSERT INTO `route` (`idroute`,`name`) VALUES (63,'35 LA PALMILLA');
INSERT INTO `route` (`idroute`,`name`) VALUES (64,'36');
INSERT INTO `route` (`idroute`,`name`) VALUES (65,'37');
INSERT INTO `route` (`idroute`,`name`) VALUES (66,'37A');
INSERT INTO `route` (`idroute`,`name`) VALUES (67,'38');
INSERT INTO `route` (`idroute`,`name`) VALUES (68,'38B');
INSERT INTO `route` (`idroute`,`name`) VALUES (69,'39');
INSERT INTO `route` (`idroute`,`name`) VALUES (70,'39A');
INSERT INTO `route` (`idroute`,`name`) VALUES (71,'39B');
INSERT INTO `route` (`idroute`,`name`) VALUES (72,'42');
INSERT INTO `route` (`idroute`,`name`) VALUES (73,'43');
INSERT INTO `route` (`idroute`,`name`) VALUES (74,'44');
INSERT INTO `route` (`idroute`,`name`) VALUES (75,'35 EL GURRIO');
